;Desktop Environment System (DES) Game
;-----------------------------------------------------;
;                                                     ;
;                  ____  _____ ____                   ;
;                 |  _ \| ____/ ___|                  ;
;                 | | | |  _| \___ \                  ;
;                 | |_| | |___ ___) |                 ;
;                 |____/|_____|____/                  ;
;      _       _                 _                    ;
;     / \   __| |_   _____ _ __ | |_ _   _ _ __ ___   ;
;    / _ \ / _` \ \ / / _ \ '_ \| __| | | | '__/ _ \  ;
;   / ___ \ (_| |\ V /  __/ | | | |_| |_| | | |  __/  ;
;  /_/   \_\__,_| \_/ \___|_| |_|\__|\__,_|_|  \___|  ;
;                                                     ;
;------------------------------------------------------
;                                                     ;
;               Written by Brian Chiha                ;
;               brian.chiha@gmail.com                 ;
;           github.com/bchiha/DES_Adventure           ;
;                                                     ;
;------------------------------------------------------

PRINT "LOADING - DES JUMPBLOCK"

NOLIST

;OUTPUT/GRAPHICAL ROUTINES
PRINTCHR    EQU  &9200 ;DISPLAYS A SINGLE CHARACTER
PRINTSTRING EQU  &9203 ;DISPLAYS A STRING OF CHARACTERS
SPACE       EQU  &9206 ;DISPLAYS A SPACE
BACKSPACE   EQU  &9209 ;PERFORMS A BACK-SPACE
TINYFONT    EQU  &920C ;SET TEXT TO "TINY" FONT
DWDFONT     EQU  &920F ;SET TEXT STYLE TO DOUBLE-WIDTH
DIMFONT     EQU  &9212 ;SET TEXT STYLE TO DIMMED
INVFONT     EQU  &9215 ;SET TEXT STYLE TO INVERSE MODE
PRINTA      EQU  &9218 ;OUTPUT VALUE IN A IN DECIMAL
PRINTHL     EQU  &921B ;OUTPUT VALUE IN HL IN DECIMAL
PRINTHEXA   EQU  &921E ;OUTPUT VALUE IN A IN HEX
PRINTHEXHL  EQU  &9221 ;OUTPUT VALUE IN HL IN HEX
LOCATE      EQU  &9224 ;SET DES CURSOR POSITION
CURSORON    EQU  &9227 ;DISPLAYS A CURSOR AT CURRENT POSITION
CURSOROFF   EQU  &922A ;REMOVES CURSOR FROM SCREEN
CLEARBOX    EQU  &922D ;CLEARS AN AREAS OF THE SCREEN
FILLBOX     EQU  &9230 ;FILLS AN AREA OF THE SCREEN WITH A VALUE
INVERTBOX   EQU  &9233 ;INVERTS COLOURS IN AN AREA OF THE SCREEN
FILEGARD    EQU  &9236 ;DISPLAYS A "FILE CARD" WINDOW
NORMBOX     EQU  &9239 ;DISPLAYS A SINGLE-LINED BOX
MENUBOX     EQU  &923C ;DISPLAYS A BOX WITH A SHADOW BEHIND IT
WINDOW      EQU  &923F ;DISPLAYS A WINDOW
ALERTBOX    EQU  &9242 ;DISPLAYS A BOX WITH A THICK BORDER
MENUBAR     EQU  &9245 ;DISPLAYS A MENU BAR
ALERTRESPONSE EQU &9248 ;GETS USER RESPONSE FROM AN ALERT BOX
BUTTON      EQU  &924B ;DISPLAYS A PUSHBUTTON
RADIOBUTTONS EQU &924E ;DISPLAYS A COLUMN OF RADIO BUTTONS
RADIOZONES  EQU  &9251 ;SETS UP CLICK ZONES FOR RADIO BUTTONS
CHECKBOXES  EQU  &9254 ;DISPLAYS A COLUMN OF CHECK BOXES
CHECKZONES  EQU  &9257 ;SETS UP CLICK ZONES FOR CHECK BOXES
DRAWICON    EQU  &925A ;DISPLAYS AN ICON
DRAWARROW   EQU  &925D ;DISPLAYS AN UP OR DOWN ARROW
DRAWGRAPHIC EQU  &9260 ;DISPLAYS A GRAPHIC BLOCK

;INPUT ROUTINES
MOUSE       EQU  &9263 ;WAITS FOR USER TO SELECT USING POINTER
MOUSEPOS    EQU  &9266 ;RETURNS POINTER COORDINATES
WAIT        EQU  &9269 ;WAITS UNTIL ALL MOUSE SELECT KEYS ARE RELEASED
FILENAME    EQU  &926C ;INPUTS AND VALIDATES A FILENAME
INPUTNUMBER EQU  &926F ;INPUTS OR EDITS A NUMBER
INPUTSTRING EQU  &9272 ;INPUTS A STRING
EDITSTRING  EQU  &9275 ;EDITS AN EXISTING STRING
STRINGZONE  EQU  &9278 ;SETS INPUT WINDOW FOR STRING EDITING
STRINGCASE  EQU  &927B ;SETS AUTOMATIC UPPER CASE CONVERSION
PULLMENU    EQU  &927E ;DISPLAY & SELECT FROM A PULL-DOWN MENU
CLEARINPUT  EQU  &9281 ;SAME AS CLEAR INPUT IN BASIC 1.1
READCHR     EQU  &9284 ;READS A SINGLE CHARACTER WITH FLASHING CURSOR

;DISC ROUTINES
FORMATDISC  EQU  &9287 ;FORMATS A DISC TO DATA/SYSTEM/ROMDOS
CHECKON     EQU  &928A ;ENABLES ADVANCED DISC ERROR CHECKING
CHECKOFF    EQU  &928D ;DISABLES ADVANCED DISC ERROR CHECKING
CHECKABANDON EQU &9290 ;ABORTS ADVANCED DISC ERROR CHECKING
READSECTOR  EQU  &9293 ;READS A SECTOR FROM DISC
WRITESECTOR EQU  &9296 ;WRITES A SECTOR TO DISC
SCANFORMAT  EQU  &9299 ;SCANS DISC & WORKS OUT FORMAT
LASTFORMAT  EQU  &929C ;RETURNS VALUES FOR FORMAT OF LAST DISC
GETDRIVE    EQU  &929F ;RETURNS CURRENT DISC DRIVE
GETUSER     EQU  &92A2 ;RETURNS CURRENT USER NUMBER
SETDRIVE    EQU  &92A5 ;SETS CURRENT DISC DRIVE
SETUSER     EQU  &92A8 ;SETS USER NUMBER
GRINDOFF    EQU  &92AB ;STOPS DRIVE GRINDING DURING READ ERROR
GRINDON     EQU  &92AE ;RESTORES DRIVE SETTINGS AFTER GRINDOFF
SCANDIR     EQU  &92B1 ;SCANS FILENAMES FROM DISC
NAMEADDR    EQU  &92B4 ;RETURNS ADDRESS OF A NAME SCANNED BY "SCANDIR"
PRINTNAME   EQU  &92B7 ;PRINTS A FILENAME SCANNED BY "SCANDIR"
CENTRENAME  EQU  &92BA ;SAME AS "PRINTNAME" EXCEPT NAME IS CENTRED

;MISCELLANEOUS ROUTINES
PRINTERONLINE EQU &92BD ;CHECKS IF PRINTER IS ON-LINE
CLRZONES    EQU  &92C0 ;CLEARS ALL CLICK ZONES FROM MEMORY
RAMZONES    EQU  &92C3 ;SETS UP CLICK ZONES FROM A LIST IN MEMORY
SETZONE     EQU  &92C6 ;SETS UP A SINGLE CLICK ZONE
ZONEADDR    EQU  &92C9 ;RETURNS ADDRESS OF "NUMBER OF ZONES" BYTE
ZONEKEYS    EQU  &92CC ;SET SHORTCUT KEYS FOR CLICK ZONE(S)
CLEARKEYS   EQU  &92CF ;CLEARS ALL SHORTEUT KEYS
PING        EQU  &92D2 ;PERFORMS THE ERROR SOUND
SCRADDR     EQU  &92D5 ;RETURNS SCREEN ADDRESS FOR A COORDINATE
NEXTLINE    EQU  &92D8 ;GET ADDRESS OF NEXT SCREEN LINE DOWN
STOREBOX    EQU  &92DB ;STORES AN AREA OF THE SCREEN IN RAM
RESTOREBOX  EQU  &92DE ;REDRAWS A STORED AREA OF THE SCREEN
LISTPREV    EQU  &92E1 ;MOVES LIST BOX POINTER UP BY 1 POSITION
LISTNEXT    EQU  &92E4 ;MOVES LIST BOX POINTER DOWN BY 1 POSITION
LISTITEM    EQU  &92E7 ;RETURNS CURRENT ITEM IN LIST BOX
LISTSELECT  EQU  &92EA ;SELECTS LIST BOX ITEM UNDER POINTER
LISTUP      EQU  &92ED ;SCROLL LIST BOX UP BY 1 POSITION
LISTDOWN    EQU  &92F0 ;SCROLL LIST BOX DOWN BY 1 POSITION
LISTINIT    EQU  &92F3 ;INITIALISE A LIST BOX
LISTDISPLAY EQU  &92F6 ;DISPLAYS VISIBLE PART OF LIST BOX
SCROLLBAR   EQU  &92F9 ;DISPLAYS A SCROLL BAR
ROMCOMMAND  EQU  &92FC ;CALLS THE "EXECUTE ROM COMMANDS" FUNCTION
GETPERCENT  EQU  &92FF ;RETURNS A PERCENTAGE FOR A VALUE
SECPERCENT  EQU  &9302 ;RETURNS PERCENTAGE FOR SECTOR POSITION
RETNUM      EQU  &9305 ;RETURNS STRING EQUIVALENT OF A NUMBER
READDIRSECS EQU  &9308 ;READS IN DIRECTORY SECTORS FROM DISC
WRITEDIRSECS EQU &930B ;WRITES DIRECTORY SECTORS TO DISC
CAMPLOGO    EQU  &930E ;DISPLAYS CAMPURSOFT LOGO
RAMTEST     EQU  &9311 ;CHECKS IF COMPUTER HAS 128K RAM
RAMBANK     EQU  &9314 ;SWITCHES IN EXTRA RAM BANKS
POKENAME    EQU  &9317 ;COPIES A FILENAME INTO MEMORY LOCATION
SELECTDRIVE EQU  &931A ;PROMPTS FOR A DISC DRIVE A OR B
TWOBUTWIN   EQU  &931D ;DISPLAYS AN OK/CANCEL WINDOW
SETMESS     EQU  &9320 ;ENABLES/DISABLES AMSDOS ERROR MESSAGES
SELECTFORMAT EQU &9323 ;SELECTS A DISC DRIVE AND FORMAT
HOLDESCBOX  EQU  &9326 ;DISPLAYS A BOX WITH "HOLD ESC TO ABORT" IN IT
HESCPERCENT EQU  &9329 ;DISPLAYS "x% COMPLETED..." IN A HOLDESCBOX
GETBLANKER  EQU  &932C ;RETURNS ADDRESS OF SCREEN BLANKER STATUS BYTE
CAMERAVEC   EQU  &932F ;CALL BY POINTER AND FLASHING CURSOR ROUTINES
DISPLAYPOINTER EQU &9332 ;NEW POINTER DISPLAY ROUTINE
CLEARPOINTER EQU &9335 ;NEW POINTER REMOVAL ROUTINE

LE CHARACTER
PR
          TEST
            fdas
            fdas

            LD A,02
            RRL
    